fix: add language mark
openRin/Rin pull request #212
Opened 2024-07-10 15:34 UTC by PBK-B

添加语言翻译，增加语言设置项标记

TBR; @OXeu

2024-07-11 10:48 UTC, OXeu requested changes

2024-07-11 10:48 UTC, OXeu commented on client/src/components/header.tsx
> +                            {i18n.language === code && (
选中语言效果请使用 text-theme 高亮文本代替小红点

2024-07-11 16:06 UTC, PBK-B commented on client/src/components/header.tsx
> +                            {i18n.language === code && (
@OXeu 我觉得小红点更炫酷

2024-07-11 23:57 UTC, OXeu commented on client/src/components/header.tsx
> +                            {i18n.language === code && (
打回

2024-07-12 01:11 UTC, PBK-B commented on client/src/components/header.tsx
> +                            {i18n.language === code && (
@OXeu 不伺候了，略略略

2024-07-12 01:11 UTC, closed without merging